env:
  global:
  - secure: wOuF5u0C3+0CBr5MFirPjG38Oat3f0TkXxP98Io5jul2OxHda4WwdSAu5ZVjP5rRVVscDQYwyoKNPDVWiVIrMmggvfuqyib3+zxWcG6pfquND9scbXlOs9biSidNFkTNTnlCOByOBPKOdmwuy066JL628fvBUdQG4dSgri617sbapldwDvUJGqk2zSXW93J3PWdYfLA4yW0aZtDgel27qGiZu6KN+BSnYV53eO8YJoVpxZTmpr7qOzOflIT0hdB7R5bz4xCgF3ruKnADtvBU0JECBJ83XeeXhccdrr+FBtYbMfmvRoyYqmGNSlqe56Tl5ZhwU7R9k3zlQGd9moito0QoqgTOO1Wf7R4T7+g/4lOqm0p/X9Vm0dyxHwRVMaaP5oDYqJByaNkRGoXTfdY8uhct79coj3/rDeBoM4tCvjOLXm/CEUyPIMA1g8X0+N79bC2gVerwaOviSXLZTAEbyQ+0YgjOdKicUo6lJKPF+Xj8PmfyNcN6uxj0Bk9qx7Km9+sEiLsi0gLgoEPb+gy++3x36b4LC3J6WcPZoo3Yp6kkxnqQjQugYZPdJTAfgkXJ6wpIwXQlCaTysu3o5dd/7P0hBOeL5EfaZMBdmH1VX0GK2HO1YWtaHcfHHuY0M/yTupOFGALWflnDpe01gA2h+wVWCm11q7HiibHdp9byZ3A=

sudo: required
services:
- docker

dist: xenial

language: bash

script:
- ./build.sh
